# Generated by Django 4.1.10 on 2023-08-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('image', models.ImageField(upload_to='movies')),
                ('story', models.TextField(max_length=1500)),
                ('creates', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
